### ISSUE TITLE
Symfony console 6.0 support

### ISSUE THREAD

**Issue by WarriorXK** [icanhazstring/symfony-console-spinner#2]
Hi there,

Is it possible that you add support for symfony console ^6.0?
According to the symfony changelog this package should be compatible.

**Comment by icanhazstring** [comment]
Hi @WarriorXK sure.
If you want you can give it a quick go and just add `|| ^6.0` in symfony/console requirement in `composer.json`.

Right now my plate is more than full with work.

**Comment by WarriorXK** [comment]
Done, see #3

**Comment by GuySartorelli** [comment]
Looks like that was merged in, this issue should be closed I think.
