### ISSUE TITLE
Allow setting the progress bar format

### ISSUE THREAD

**Issue by GuySartorelli** [icanhazstring/symfony-console-spinner#4]
The format of this spinner is fixed, and the underlying progressbar is `private`, so the format can't be overridden.
I want to add a `%elapsed:6s%` to the end of the progressbar format so I have an indication of how long the process has been running for.

I'd be happy to create a PR to add this in. I'm relaxed about whether there's a way to access the underlying progress bar or if there's a `setFormat()` method, or some other mechanism - let me know what you'd prefer and I'll open a PR if you're open to it.

**Comment by icanhazstring** [comment]
Hi. Sounds good. Go ahead 👍

**Comment by GuySartorelli** [comment]
Sweet.
https://github.com/icanhazstring/symfony-console-spinner/pull/6

I also added another PR tidying up the README while I was in there - done separately so that if you don't like it you can just close it but still merge the one above.
